util.AddNetworkString("LevelUpdate")
util.AddNetworkString("GetLevel")
net.Receive("reward1",function(len,ply)
	ply:ChatPrint("You reached Level 1! You unlocked /model command!")
	net.Start("LevelUpdate")
		net.WriteInt(1,16)
	net.Send(ply)
end)
net.Receive("reward2",function(len,ply)
	ply:ChatPrint("You reached Level 2! You unlocked /color command!")
	net.Start("LevelUpdate")
		net.WriteInt(2,16)
	net.Send(ply)
end)
net.Receive("reward1",function(len,ply)
	ply:ChatPrint("You reached Level 3! You unlocked /armor command!")
	net.Start("LevelUpdate")
		net.WriteInt(3,16)
	net.Send(ply)
end)
function GetLevel(ply)
	net.Start( "GetLevel" )
	net.Send( ply )
end
hook.Add("PlayerSay","modelchanging_1", function(ply,text,team) 
	if ()
end)
