util.AddNetworkString("LevelUpdate")
util.AddNetworkString("GetLevel")
util.AddNetworkString("reward1")
util.AddNetworkString("reward2")
util.AddNetworkString("reward3")
util.AddNetworkString("alyx_model")
util.AddNetworkString("odessa_model")
util.AddNetworkString("gman_model")

function AnnounceLevel(ply,level)
	for _,p in pairs(player.GetAll()) do
		p:ChatPrint(ply:Nick().." reached Level "..level.."!")
	end
end

local llevel = 0
net.Receive("reward1",function(len,ply)
	ply:ChatPrint("You reached Level 1! You unlocked /model command!")
	net.Start("LevelUpdate")
		net.WriteInt(1,16)
	net.Send(ply)
end)
net.Receive("reward2",function(len,ply)
	ply:ChatPrint("You reached Level 2! You unlocked /color command!")
	net.Start("LevelUpdate")
		net.WriteInt(2,16)
	net.Send(ply)
end)
net.Receive("reward3",function(len,ply)
	ply:ChatPrint("You reached Level 3! You unlocked /armor command!")
	net.Start("LevelUpdate")
		net.WriteInt(3,16)
	net.Send(ply)
end)
net.Receive("alyx_model",function(len,ply)
	local m = net.ReadString()
	ChangeModel(ply,m)
end)
net.Receive("odessa_model",function(len,ply)
	local m = net.ReadString()
	ChangeModel(ply,m)
end)
net.Receive("gman_model",function(len,ply)
	local m = net.ReadString()
	ChangeModel(ply,m)
end)
function GetLevel(ply)
	net.Start( "GetLevel" )
	net.Send( ply )
	llevel = net.ReadInt(16)
end